[package]
name = "alixt-table"
version = "0.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/D-H0f/alixt-table"
description = "A table rendering library for CLIs"
keywords = ["cli", "table", "tui", "formatting", "output"]
categories = ["command-line-interface", "visualization"]
readme = "README.md"

[dependencies]
colored = "3.0.0"
thiserror = "2.0.17"
